format_error: Drop inadvertent newline added to conditional error messages
A newline was inadvertently added to the start of the output of
conditional error messages.

Signed-off-by: Rob Herring (Arm) <robh@kernel.org>